//
//  ColorPalette.swift
//  TrainSwift
//
//  Centralized color definitions.
//  All colours live in Assets.xcassets/Colors/ as colour sets with
//  Light and Dark appearance variants. SwiftUI resolves the correct
//  variant automatically based on the active colour scheme.
//

import SwiftUI
import Combine

// MARK: - Theme Mode

/// Theme mode selection
enum AppThemeMode {
    case dark
    case light
}

/// Theme Manager — persists the user's light/dark preference
@MainActor
class ThemeManager: ObservableObject {
    @Published var currentMode: AppThemeMode

    init() {
        let savedMode = UserDefaults.standard.string(forKey: "AppThemeMode")
        self.currentMode = savedMode == "light" ? .light : .dark
    }

    func setTheme(_ mode: AppThemeMode) {
        currentMode = mode
        UserDefaults.standard.set(mode == .light ? "light" : "dark", forKey: "AppThemeMode")
    }
}

// MARK: - Adaptive Colours (Asset Catalog — auto light/dark)
//
// Primary colours are auto-generated by Xcode from Assets.xcassets/Colors/:
//   .trainPrimary, .trainBackground, .trainDark, .trainSurface,
//   .trainGradientLight/Mid/Dark, .trainTextPrimary/Secondary/Muted,
//   .trainBorderSubtle/Default/Strong, .trainDisabled, .trainTimelineLine
//
// The aliases below map legacy names to their canonical colour sets.

extension Color {
    // Short-name aliases → canonical colour sets
    static let trainSecondary = Color(.trainTextSecondary)
    static let trainLight = Color(.trainPrimaryLight)
    static let trainHover = Color(.trainPrimaryHover)

    // Legacy gradient aliases
    static let trainGradientEdge = Color(.trainGradientDark)
    static let trainGradientCenter = Color(.trainGradientMid)

    // Border alias
    static let trainBorder = Color(.trainBorderDefault)

    // Disabled alias
    static let trainMutedFill = Color(.trainDisabled)
}

// MARK: - Semantic Colors (consistent across themes)

extension Color {
    /// Success indicator (green) - progressive overload, completion, etc.
    static let trainSuccess = Color(hex: "4DCA73")
    /// Warning indicator (orange/amber)
    static let trainWarning = Color.orange
    /// Error indicator (red)
    static let trainError = Color.red
    /// Info indicator (blue)
    static let trainInfo = Color.blue
    /// Placeholder/thumbnail background
    static let trainPlaceholder = Color.gray.opacity(0.3)
    /// Equipment tag background
    static let trainTag = Color.gray
    /// Tab selector background (light mode)
    static let trainTabBackground = Color(hex: "E2E3E4")
}

// MARK: - On-Primary / Contrast Colors

extension Color {
    /// Dark text color for use ON primary (orange) backgrounds — ensures WCAG AA contrast
    static let trainTextOnPrimary = Color(hex: "1a1a2e")
}

// MARK: - Component-Specific Colors

extension Color {
    /// Muscle diagram — default unselected fill
    static let trainMuscleDefault = Color(hex: "3f3f3f")
    /// Muscle diagram — inactive/non-highlighted parts
    static let trainMuscleInactive = Color(hex: "8a8a8a")
}

// MARK: - Confetti Colors

extension Color {
    /// Decorative confetti palette for celebrations
    static let trainConfetti: [Color] = [
        Color(hex: "FF6B6B"),   // coral red
        Color(hex: "4ECDC4"),   // teal
        Color(hex: "FFE66D"),   // golden yellow
        Color(hex: "95E1D3"),   // mint
        Color(hex: "F38181"),   // salmon pink
    ]
}

// MARK: - Input Border Colors (adaptive — replaces manual colorScheme branching)

extension Color {
    /// Input field border — light mode: dark, dark mode: translucent white
    static let trainInputBorder = Color(.trainBorderDefault)
    /// Input field border (subtle) — for dashed/secondary borders
    static let trainInputBorderSubtle = Color(.trainBorderSubtle)
}
